<a href="https://colab.research.google.com/github/krishnanjaliiyersr-lang/ICT_DSA_CASE_STUDY/blob/main/casestudy_acquisition_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Acquisitionand Analysis of SpaceX Launch Data

###Load SpaceX Launch Data

Step 1: Load SpaceX Launch Data from API
● Use https://api.spacexdata.com/v4/launches
● Extract relevant columns: name, date_utc, success, details, rocket
● Convert date_utc to datetime and extract the year

In [18]:
import pandas as pd
import requests

# URL for SpaceX launches API
url_launches = "https://api.spacexdata.com/v4/launches"

# Fetch data from the API
response = requests.get(url_launches)

# Convert API response to JSON format (Python dictionary/list)
launch_data = response.json()

# Convert JSON data into a Pandas DataFrame for better readability
launch_df = pd.DataFrame(launch_data)

# Keep only the required columns
# Double brackets are used to select multiple columns
launch_df = launch_df[['name', 'date_utc', 'success', 'details', 'rocket']]

# Convert 'date_utc' from text (string) to datetime format
# This helps in performing date-based operations
launch_df['date_utc'] = pd.to_datetime(launch_df['date_utc'])

# Extract only the year from the datetime column
# .dt is used to access datetime properties
launch_df['year'] = launch_df['date_utc'].dt.year

# Display the first 5 rows of the DataFrame
launch_df.head()

,name,date_utc,success,details,rocket,year
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009

### Load Rocket Metadata
● Use https://api.spacexdata.com/v4/rockets
● Extract id, name, type, active, and stages

In [ ]:
url_rockets= "https://api.spacexdata.com/v4/rockets"
response= requests.get(url_rockets)
rocket_data= response.json()
rocket_df= pd.DataFrame(rocket_data)

# Extract column
rocket_df= rocket_df[['id','name','type','active','stages']]

rocket_df.head()

                         id          name    type  active  stages
0  5e9d0d95eda69955f709d1eb      Falcon 1  rocket   False       2
1  5e9d0d95eda69973a809d1ec      Falcon 9  rocket    True       2
2  5e9d0d95eda69974db09d1ed  Falcon Heavy  rocket    True       2
3  5e9d0d96eda699382d09d1ee      Starship  rocket   False       2

###Merge Launch & Rocket Data

###Join the two DataFrames on rocket ID using

In [ ]:
#left_on → column name in the left DataFrame
#right_on → column name in the right DataFrame
#how ='left'It means LEFT JOIN
#Keep ALL rows from the left table (launch_df)
#Add matching data from the right table

merged_df=pd.merge(launch_df,rocket_df,left_on='rocket',right_on='id',how='left')
merged_df.head()

,name_x,date_utc,success,details,rocket,year,id,name_y,type,active,stages
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2

#Add Simulated Country Information
● Add a new column country and randomly assign one of these values:
['USA', 'Russia', 'India', 'China', 'France']

In [ ]:
import random

# this creates a new column country,
#random.choice(countries):(Picks one random country from the list),

countries=['USA','Russia','India','China','France']
merged_df['country']=[random.choice(countries) for _ in range (len(merged_df))]
merged_df.head(5) # show the top 5 row

,name_x,date_utc,success,details,rocket,year,id,name_y,type,active,stages,country
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,USA
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,Russia
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,China
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,India
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,France

### Store Merged Data in SQLite3
● Use sqlite3 to create a connection and save the merged DataFrame as a table named
launches
● Table should contain all merged columns including country

In [ ]:
import sqlite3

conn = sqlite3.connect("spacex.db")

merged_df.to_sql("launches", conn, if_exists="replace", index=False)

print("Data stored successfully!")

Data stored successfully!

In [15]:
#To show table contain all merged values
query = "SELECT * FROM launches LIMIT 5;"
pd.read_sql(query, conn)

,name_x,date_utc,success,details,rocket,year,id,name_y,type,active,stages,country
0,FalconSat,2006-03-24 22:30:00+00:00,0,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,0,2,USA
1,DemoSat,2007-03-21 01:10:00+00:00,0,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,0,2,Russia
2,Trailblazer,2008-08-03 03:34:00+00:00,0,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,0,2,China
3,RatSat,2008-09-28 23:15:00+00:00,1,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,0,2,India
4,RazakSat,2009-07-13 03:35:00+00:00,1,None,5e9d0d95eda69955f709d1eb,2009,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,0,2,France

# Run SQL Queries

###Launches by Country

In [ ]:
q1 = """
SELECT country, COUNT(*) AS total_launches
FROM launches
GROUP BY country
ORDER BY total_launches DESC;
"""

pd.read_sql(q1, conn)

  country  total_launches
0  France              50
1   China              41
2   India              40
3  Russia              39
4     USA              35

### Year with Highest Launches

In [16]:
q2 = """
SELECT year, COUNT(*) AS total_launches
FROM launches
GROUP BY year
ORDER BY total_launches DESC
LIMIT 1;
"""

pd.read_sql(q2, conn)

   year  total_launches
0  2022              62

### Top 5 Missions by Launch Count

In [17]:
q3 = """
SELECT name_x, COUNT(*) AS launch_count
FROM launches
GROUP BY name_x
ORDER BY launch_count DESC
LIMIT 5;
"""

pd.read_sql(q3, conn)

                      name_x  launch_count
0  ispace Mission 1 & Rashid             1
1                       ZUMA             1
2     WorldView Legion 1 & 2             1
3        Viasat-3 & Arcturus             1
4                    USSF-44             1

In [19]:
conn.close()